[package]
name = "toy-jwt"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = { version = "10.2.0", features = ["aws_lc_rs"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"

[dev-dependencies]
