[package]
name = "toy-pack-yaml"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2021"

[dependencies]
thiserror = "2"
serde = { version = "1.0" }
serde_yaml = "0.9"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
