[package]
name = "toy-map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.12.0"
serde = { version = "1.0" }

toy-pack = { path = "../toy-pack", features = ["derive"] }
