[package]
name = "toy-rt"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["rt-multi-thread", "sync", "time", "tracing", "net"] }

toy-core = { path = "../toy-core" }
