[package]
name = "toy-pack-urlencoded"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "2"
serde = { version = "1.0" }
serde_urlencoded = "0.7"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
