[package]
name = "toy-pack-mp"
version = "0.1.0"
authors = ["defvar <def.daisuke@gmail.com>"]
edition = "2021"

[dependencies]
lazy_static = "1.2.0"
thiserror = "2"
toy-pack = { path = "../toy-pack" }
serde = { version = "1.0" }

[dev-dependencies]
rmp = "^0.8"
rmpv = "1.3"
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }
