[package]
name = "toy-tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "time"] }
tracing-appender = "0.2"
console-subscriber = { version = "0.5.0" }
thiserror = "1.0"
