[package]
name = "toyterm"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
clap = { version = "4.0.32", features = ["derive", "env"] }
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
ratatui = "0.29.0"
tokio = { version = "1.48", features = ["sync", "macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.17", features = [] }
rand = "0.9.2"

toy-rt = { path = "../../../pkg/toy-rt" }
toy-pack-json = { path = "../../../shared/toy-pack-json" }
toy = { path = "../../../pkg/toy", features = ["api-client"] }
toy-jwt = { path = "../../../shared/toy-jwt" }
toy-pack-urlencoded = { path = "../../../shared/toy-pack-urlencoded" }
